apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 586673455626.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 586673455626.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: e6a05a0a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
