apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 996439551564.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 996439551564.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 8f9b02e0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
